// 定义一个Schema
const mongoose = require('mongoose')

module.exports = new mongoose.Schema({
    'sid':String,
    'cal1_m':Number,
    'cal1_f':Number,
    'linear_m':Number,
    'linear_f':Number,
    '1_lib':Number,
    '2_lib':Number,
    '3_lib':Number,
    '4_lib':Number,
    '5_lib':Number,
    '6_lib':Number,
    '7_lib':Number,
    '8_lib':Number,
    '9_lib':Number,
    '10_lib':Number,
    '11_lib':Number,
    '12_lib':Number,
    '1_hw':Number,
    '2_hw':Number,
    '3_hw':Number,
    '4_hw':Number,
    '5_hw':Number,
    '6_hw':Number,
    '7_hw':Number,
    '8_hw':Number,
    '9_hw':Number,
    '10_hw':Number,
    '11_hw':Number,
    '12_hw':Number,
})
